[package]
name = "typst-ppt-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
typst = "0.14"
typst-svg = "0.14"
typst-eval = "0.14.2"
chrono = { version = "0.4", features = ["wasmbind"] }